version: '3.8'

services:
  backend:
    build: ./gestion-de-stock-api-master
    container_name: stock-management-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gestionstock?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db
    networks:
      - stock-network

  frontend:
    build: ./gestion-de-stock-frontend-master
    container_name: stock-management-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - stock-network

  db:
    image: mysql:8.0
    container_name: stock-management-db
    restart: always
    environment:
      - MYSQL_DATABASE=gestionstock
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  db-data:
